apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: telegraf-ds
  namespace: monitoring
spec:
  releaseName: telegraf-ds
  chart:
    spec:
      chart: telegraf-ds
      version: "~1.0.29"
      sourceRef:
        kind: HelmRepository
        name: influxdata
  interval: 5m0s
  targetNamespace: monitoring
  values:
    config:
      outputs:
        - influxdb:
            urls:
              - "http://influxdb-influxdb2.monitoring.svc:80"
            retention_policy: "3d"
      monitor_self: true