---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: mojo2600
spec:
  interval: 10m0s
  url: https://mojo2600.github.io/pihole-kubernetes/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
spec:
  releaseName: pihole
  targetNamespace: pihole
  chart:
    spec:
      chart: pihole
      version: "~2.5.8"
      sourceRef:
        kind: HelmRepository
        name: mojo2600
  interval: 5m0s
  values:
    admin:
      existingSecret: "pihole-auth"
      passwordKey: "password"
    persistentVolumeClaim:
      enabled: true
      size: "500Mi"
      storageClass: "longhorn"
    DNS1: 1.1.1.1
    DNS2: 8.8.8.8
    serviceWeb:
      type: LoadBalancer
      loadBalancerIP: 10.0.0.53
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
    serviceDns:
      type: LoadBalancer
      loadBalancerIP: 10.0.0.53
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc