---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./cluster-infra/metallb
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-personal