---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: home-assistant
  namespace: flux-system
spec:
  # decryption:
  #   provider: sops
  #   secretRef:
  #     name: sops-gpg
  interval: 10m0s
  path: ./apps/home-assistant
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-personal