---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: influxdb
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/influxdb
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-personal