---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: influxdb
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  interval: 10m0s
  path: ./infrastructure/influxdb
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-personal
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: telegraf-ds
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  interval: 10m0s
  path: ./infrastructure/telegraf-ds
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-personal