---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: jetstack
spec:
  interval: 10m0s
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  releaseName: cert-manager
  interval: 5m0s
  chart:
    spec:
      chart: cert-manager
      version: "~1.7.1"
      sourceRef:
        kind: HelmRepository
        name: jetstack
  targetNamespace: cert-manager
  values:
    global:
      leaderElection:
        # Override the namespace used to store the ConfigMap for leader election
        # This was kube-system by default
        namespace: cert-manager
    prometheus:
      enabled: false
    installCRDs: true
