---
- hosts: cluster
  become: no
  tasks:
    - name: Get top processes
      shell: ps -eo pcpu,user,args | sort -r -k1 | head -n5
      register: ps
      changed_when: False

    - name: debug
      debug: var=ps.stdout_lines