---
- hosts: cluster
  become: yes
  tasks:
    # Get list of apt packages to check for snapd being installed
    - name: Gather The Package Facts (apt)
      ansible.builtin.package_facts:
        manager: apt

    # Uninstall all existing snaps if snapd was installed
    - name: Uninstall Snaps
      community.general.snap:
        name: "{{ item }}"
        state: absent
      loop:
        - lxd
        - core18
        - core20
        - snapd
      check_mode: no
      when: "'snapd' in ansible_facts.packages"

    # List installed snaps to check that none are installed in next step
    - name: Get List of Installed Snaps - Shell
      ansible.builtin.shell: snap list | tail -n +2 | awk '{print $1}'
      register: installed_snaps
      changed_when: no
      when: "'snapd' in ansible_facts.packages"
    
    # Debug statement to fail if there are still snaps installed
    - name: Skip if all snaps are uninstalled
      ansible.builtin.debug:
        msg: "Please remove the following snaps: {{ installed_snaps.stdout | replace('\n', ', ') }}"
      when: 
        - "'snapd' in ansible_facts.packages"
        - "'No snaps are installed' not in installed_snaps.stderr"
      failed_when: yes
    
    # Stop the snapd service so we can uninstall it
    - name: Stop Service - snapd
      ansible.builtin.service:
        name: snapd
        enabled: no
        state: stopped
      register: snapd_service
      when: "'snapd' in ansible_facts.packages"

    # Wait for a few second to allow the service to stop
    - name: Sleep for 30 seconds and continue with play
      wait_for:
        timeout: 30
      when: snapd_service.changed

    # Purge snapd from apt
    - name: Purge snapd From apt
      ansible.builtin.apt:
        name:
          - snapd
        purge: yes
        state: absent
    
    # List all users so we can remove ~/snapd fro all of them
    - name: Get List User Directories in /home
      ansible.builtin.shell: ls /home
      register: users
      changed_when: no
    
    # Remove ~/snapd from all home directories
    - name: Remove snapd Files In User Directories
      ansible.builtin.file:
        path: "/home/{{ item }}/snapd"
        state: absent
      loop: "{{ users.stdout_lines }}"

    # Remove all of the snapd files from the rest of the system
    - name: Remove snapd Files That Are Left
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /snap
        - /var/snap
        - /var/lib/snapd
        - /var/cache/snapd
        - /usr/lib/snapd
    
    # Clean up any dependencies snap installed in apt
    - name: Remove dependencies that are no longer required
      ansible.builtin.apt:
        autoremove: yes
    
    # Disable packages from installing snap in the future
    - name: Copy In no-snap Preference
      ansible.builtin.copy:
        dest: /etc/apt/preferences.d/no-snap.pref
        content: |
          # To install snapd, specify its version with 'apt install snapd=VERSION'
          # where VERSION is the version of the snapd package you want to install.
          Package: snapd
          Pin: release a=*
          Pin-Priority: -10