---
- hosts: cluster
  become: yes
  tasks:
    - name: Set Facts
      set_fact:
        cmdline_txt_path: /boot/firmware/cmdline.txt

    # Read in file as base64
    - name: Read cmdline.txt
      become: true
      ansible.builtin.slurp:
        src: "{{ cmdline_txt_path }}"
      register: ret_cmdline

    - name: Set cgroup args for cmdline.txt
      ansible.builtin.shell:
        cmd: sed -i '$ s/$/ {{ item }}/' {{ cmdline_txt_path }}
      when: item not in ret_cmdline.content|b64decode
      loop:
        - cgroup_enable=cpuset
        - cgroup_enable=memory
        - cgroup_memory=1
        - swapaccount=1

    # Set iptables rules for k3s
    - name: Set iptables rules
      ansible.builtin.copy:
        dest: /etc/sysctl.d/k3s.conf
        owner: root
        group: root
        mode: 0644
        content: |
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1

    - name: Reboot
      reboot:
        msg: "Reboot initiated by Ansible"