apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-assistant
resources:
  - namespace.yaml
  - persistent-volume.yaml
  - deployment.yaml
  - service.yaml
  - ingressroute.yaml