---
# Source: home-assistant/templates/common.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: home-assistant-config
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "512Mi"