apiVersion: v1
kind: Secret
metadata:
    name: influxdb-auth
type: Opaque
data:
    admin-password: ENC[AES256_GCM,data:N9LNRuFOOlqy2y0m1kqc8xI1NCA=,iv:X6AP2Bw+83yC+hB0L9tqEMiv/7CEqYucZtFb2oiWxXE=,tag:F6NQJZFx1Al20sISCpVxUA==,type:str]
    admin-token: ENC[AES256_GCM,data:RzjYB4+8oJxNkk/GlIs7r8NCqvXojCWBuxbi7Z+T/bpLzSJrrYwaQW8mFio=,iv:vFs8A8P3Rvyp+xSc0h07sjU5rcLDLF8ImVXQGKAD9TI=,tag:y6xQ73cn5MVgBr9LApEHXQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-02-17T02:02:05Z"
    mac: ENC[AES256_GCM,data:fCXu7FCXjxzRIGPizNiC8lzt+ZTmClExV1vxykteOCS40oEmcA3Afj8KI7JrejjLK/8e20Pv9k+R0idf16nx0Pk5kRHr4Q30/jbKdKwjUgXlZjkryHhC7rKT/N2SurtG32iEGQIonxRvrEjcJmGRZfXIJvY05pdeuirBKESfdSI=,iv:Soz7QELDh3RW/HrbI9PfiG4RIMTSbaxZ3oD54pgjPUo=,tag:a5N9/cUggn/pg3h8su1Xew==,type:str]
    pgp:
        - created_at: "2022-02-15T17:46:52Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAzRgeFoHkc8aARAAqiL/WhlMsTTKnh6bshRQGqnL5RfomnXzfSuZFTykstxM
            qgXR6/2Y2rD8JWurhJ7HdgVNmdfe7HqHnlacOb4Y19zIZiLD1g/6rLwBnKa8YAdc
            9a1QUelnj71NmDu/Wnd1XD4aNBCz8vaqEIUpilgqA5J6DkDGS9UAfgpyW5kx8h0g
            FwduSGPH0MSTf3HQjlt16zz9DE/amsXRVxvWVQkTfiDMZO+hPcoPWaXQ0uHQPK6m
            coB1PfFehOpSIYE0Xr2WSCSxv50eEPlDTK4UWNPTFqadYR9Y1DyM7yxYhxYWgwB+
            vbPsUcXIADWwomosr6APjGotIiZVZaeXWM3XNT5iWhiu3JzgBRsWIvjbx7iepW9a
            WUgRNf3YEyGljcKA/3x8nywlYZETV2mqBHuEzEdGMn6NPmhzIAfqFC9ssIrUps5m
            U69vlt9Ee7RawXnW0W1Kkr2UuKRsv/4Jv9JuvnTzLBYUjnt+q9KRdfWcogFJ0Sr5
            gSezrhU7kla4mmIIIYNYU2ZEiTFlHU6R5UEBlGk4D6dPwVOOcjA9uwlPc7a1Rf+d
            nZL3sNqHuN/0edyEZIQz+G5/rAVyhgey/ROSwS8JwkVCCZfEsEw0v3HlODlwLrZM
            a5B4VpxyrF2VCuHfcaSiVQfnPCxTI/0QLJdacfM4GwjF208ksGb7ArPzstoChPzU
            ZgEJAhCjlPg2WAcsy9Gv8SILi3azz6n6kmJuE6j9uJWjQ+n4n2XsAHUhzAFmWbE7
            bHVHUWuwm72V0kHXvRKdWquvuSgdxOwiLYcKKl12Eyhx1i/6hJDUCeup+d04ge/z
            hhkhetAj+Q==
            =eo8P
            -----END PGP MESSAGE-----
          fp: 97035DBA837B72727A922DD16F33B78B284BE27E
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
