---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: influxdata
  namespace: monitoring
spec:
  interval: 10m0s
  url: https://helm.influxdata.com/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: influxdb
  namespace: monitoring
spec:
  releaseName: influxdb
  chart:
    spec:
      chart: influxdb2
      version: "~2.0.9"
      sourceRef:
        kind: HelmRepository
        name: influxdata
  interval: 5m0s
  targetNamespace: monitoring
  values:
    adminUser:
      organization: varnost
      existingSecret: influxdb-auth
    persistence:
      enabled: true
      storageClass: longhorn
      size: 5Gi
