apiVersion: v1
kind: Secret
metadata:
    name: traefik-auth
    namespace: traefik-system
data:
    users: ENC[AES256_GCM,data:9NUuh+WXTmSVJgjwRIIdJ2UL4jdzT7Yq/VDJs4J0zAGdUImjja/2lfzV3aQ81RJA2C2iTlHtHjcsXl4kAXiAS531zmBfpUXK4+JLqucQTgCY/jzx6dJeepk=,iv:eC3eOKMhYZ8nQB4PxgjdEOf549gYtprSZBt6JX7/L08=,tag:goF2r4cXI/2ykEXpHQrfeA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-02-20T18:26:04Z"
    mac: ENC[AES256_GCM,data:QRu3K4V8t3SyYsSV8oWhnBRZ0RfnwDtLkigBI+YrzoyfbLmTneNkp7Bkrs5kMY3PsV44FCiSwADskRqV9Vjg/8eu3SpwDJ5KccgbwkvHMna2ncXUEW8Uc9OZJEcymr0MIZdvxwpPYmuM5KExtD/T3qYtrxvSX1G7Gan5oAfztQ0=,iv:HFpkrY/JVkcXLy+O0eyiHdU5LP97wavvkDL20rrAOew=,tag:MpXgTsinLAK1R6R6NHlLjw==,type:str]
    pgp:
        - created_at: "2022-02-20T18:26:03Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAzRgeFoHkc8aAQ/+OGqFakpWu40aGtVivFcPNR3LTqw68C/Zfuxkh81YOnVC
            /ph8x73wJD2UiDRe+Arl0KkVNeA3hjp4qUO+AvHowTGtr1R9ZeEnXHRUOsioVpHV
            S7TzUr1BqriOU2uDh+JFBe+WTIyomPrwVbUKNTbgps6L8Q6SafmzImGFv8H/yJ6S
            x2J25g6C1BN+6Zi4PQVUmdbh9jJiK/g03b0ohDfsPJEWbdKWbF+jZSqI6XOYw7kE
            p13Al0/rSDTSqwe7gX/IxMIGIsCL0sFHdqoyihVE8uck72FC1c2kK03o/wtOf2h1
            oDf8Pi+S85KIITu17PqjjMv0t6DAjPi9QHffI2tN67ku/p59Q7MBzfo3bFF2vOQY
            dD/pw6fd3Kwt+LNOqQMSddC3Y2X7zl/uqTL7EBE1Eq6Wv4ioTYE6LNXvUKfeBGoY
            0GPB7mdIoFPrmooV+/ZfC9ye4SD0ibb3MEPISeh7aSZlkITIrB9ZCbyMHGpOBvHz
            Lwt/E0u7pbg7IH511p0VRR/ODfjxMfpTDRloe/dx1cArKZMsOxLL07KVwjdPRzit
            7SQb09q9lqjW3l9D+wjFfsI0lwoSz5Jk78WUjJA671APfTPYq6U2vLRh82C9/xVj
            ehjCHNslchFSgElbMFOhW9B5CNuHW7QumRqkRPGgV/r5p/xf7MRGigWk2qudgvvU
            aAEJAhA7CtbsIGliNyr6nM+QGaCiP4h70fL7LLK/rLAfApGLxl59mWUamJn2sEvy
            kGySTQ5wNqWC3djZ7RdLPgGjYE0u92PJnWvPYKZeJOjcegjC3olIBTCslKqtyRTp
            VbaqV2qfU7s+
            =6EUH
            -----END PGP MESSAGE-----
          fp: 97035DBA837B72727A922DD16F33B78B284BE27E
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
