---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: traefik
  namespace: traefik-system
spec:
  interval: 10m0s
  url: https://helm.traefik.io/traefik
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik-system
spec:
  releaseName: traefik
  chart:
    spec:
      chart: traefik
      version: "~10.14.1"
      sourceRef:
        kind: HelmRepository
        name: traefik
  values:
    service:
      spec:
        loadBalancerIP: 10.0.0.50
    additionalArguments:
      - "--certificatesresolvers.letsencrypt.acme.email=tylerhoyt93+letsencrypt@gmail.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
    persistence:
      enabled: true
      storageClass: longhorn
      size: 128Mi
  interval: 5m0s
  targetNamespace: traefik-system

